spring:
  datasource:
    url: jdbc:mysql://localhost:3306/JDBCPRAC?serverTimezone=UTC&characterEncoding=UTF-8
    username: takim
    password: taeh2020
    driver-class-name: com.mysql.cj.jdbc.Driver